library(choroplethr)
library(choroplethrMaps)
library(mapproj)
library(ggplot2)

data(df_county_demographics)

states <<- list("California" = "california",
                "Texas" = "texas",
                "Ohio" = "ohio",
                "Washington" = "washington",
                "Oregon" = "oregon",
                "West Virginia" = "west virginia",
                "Georgia" = "georgia",
                "New York" = "new york",
                "Hawaii" = "hawaii",
                "Alaska" = "alaska",
                "Minnesota" = "minnesota",
                "North Dakota" = "north dakota",
                "South Dakota" = "south dakota",
                "Rhode Island" = "rhode island",
                "New Mexico" = "new mexico",
                "Alabama" = "alabama",
                "Arizona" = "arizona",
                "Colorado" = "colorado",
                "Connecticut" = "connecticut",
                "Delaware" = "delaware",
                "Florida" = "florida",
                "Idaho" = "idaho",
                "Illinois" = "illinois",
                "Indiana" = "indiana",
                "Iowa" = "iowa",
                "Kansas" = "kansas",
                "Louisiana" = "louisiana",
                "Kentucky" = "kentucky",
                "Maine" = "maine",
                "Maryland" = "maryland",
                "Massachusetts" = "massachusetts",
                "Michigan" = "michigan",
                "South Dakota" = "south dakota",
                "North Dakota" = "north dakota",
                "South Carolina" = "south carolina",
                "North Carolina" = "north carolina",
                "Virginia" = "virginia",
                "Utah" = "utah",
                "Vermont" = "vermont",
                "Wisconsin" = "wisconsin",
                "Wyoming" = "wyoming",
                "Utah" = "utah",
                "Texas" = "texas",
                "Tennessee" = "tennessee",
                "Arkansas" = "arkansas",
                "Mississippi" = "mississippi",
                "Missouri" = "missouri",
                "Montana" = "montana",
                "Nebraska" = "nebraska",
                "Nevada" = "nevada",
                "New Hampshire" = "new hampshire",
                "New Jersey" = "new jersey",
                "Oklahoma" = "oklahoma",
                "Pennsylvania" = "pennsylvania")

demographic <<- list("White" = "percent_white",
                     "Black" = "percent_black",
                     "Asian" = "percent_asian",
                     "Hispanic" = "percent_hispanic",
                     "Per Capita Income" = "per_capita_income",
                     "Median Rent" = "median_rent",
                     "Median Age" = "median_age")

